### ISSUE TITLE
Enumerable not implemented

### ISSUE THREAD

**Issue by hamann** [atabary/timex-interval#3]
I've tried your examples, but this one doesn't work

``` sh
$  iex --version
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.0.5
$ grep timex mix.lock
  "timex": {:hex, :timex, "0.16.2"},
  "timex_interval": {:git, "git://github.com/atabary/timex-interval.git", "d599d888cdb26fac68e500a24f21f7f3155a3a85", []},
```

``` elixir
iex(4)> use Timex
nil
iex(5)> alias TimexInterval.DateTimeInterval, as: Interval
nil
iex(6)> Interval.new(from: Date.from({2014, 9, 22}), until: [days: 3]) |> Enum.map(fn(dt) -> DateFormat.format!(dt, "%Y-%m-%d", :strftime) end)
** (Protocol.UndefinedError) protocol Enumerable not implemented for %TimexInterval.DateTimeInterval{from: %Timex.DateTime{calendar: :gregorian, day: 22, hour: 0, minute: 0, month: 9, ms: 0, second: 0, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2014}, left_open: false, right_open: true, step: [days: 1], until: %Timex.DateTime{calendar: :gregorian, day: 25, hour: 0, minute: 0, month: 9, ms: 0, second: 0, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2014}}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:981: Enum.map/2
```

**Comment by hamann** [comment]
After reading the code which looks ok for me, I successfully tested it in two other projects. I don't know what's the reason, but it's most likely not timex-interval, so closing it.
